Email dev
Reevak05/StudentCommunityBot pull request #43
Opened 2021-07-29 07:51 UTC by Reevak05

closes #17

merge #42 before merging this PR

2021-07-29 20:25 UTC, MetalTurtle18 requested changes
Minor edits for most files. Please discuss any issues you have with my feedback.

2021-07-29 20:25 UTC, MetalTurtle18 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +    override fun onGuildMemberJoin(@Nonnull event: GuildMemberJoinEvent) {
Why is there a Nonnull annotation in Kotlin?

2021-07-29 20:25 UTC, MetalTurtle18 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                    }
```kotlin
var code: String
do {
    code = (rand.nextInt(9000) + 1000).toString()
} while (setupChannels.any { code in it.verificationCodes })
verificationCodes.add(code)
```

2021-07-29 20:25 UTC, MetalTurtle18 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                    message = "We’re sorry, but the email address you entered is invalid.",
No need to be sorry.

2021-07-29 20:25 UTC, MetalTurtle18 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                        message = "We’re sorry, but that was an invalid response. Please follow the instructions above.",
No need to be sorry.

2021-07-29 20:25 UTC, MetalTurtle18 commented on src/main/kotlin/io/github/reevak05/util/ConfigurationHandler.kt
> +    val userHtml: String
Maybe you could make a wrapper class for all of these? `EmailConfig` or something similar?

2021-07-29 21:52 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/util/ConfigurationHandler.kt
> +    val userHtml: String
Implemented in 60b81fcdb459df003a1462bd2447480c92b2a5bc

2021-07-29 21:52 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                        message = "We’re sorry, but that was an invalid response. Please follow the instructions above.",
Implemented in 60b81fcdb459df003a1462bd2447480c92b2a5bc

2021-07-29 21:52 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                    message = "We’re sorry, but the email address you entered is invalid.",
Implemented in 60b81fcdb459df003a1462bd2447480c92b2a5bc

2021-07-29 21:52 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +                    }
Implemented in 60b81fcdb459df003a1462bd2447480c92b2a5bc

2021-07-29 21:52 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/events/MemberSetupHandler.kt
> +    override fun onGuildMemberJoin(@Nonnull event: GuildMemberJoinEvent) {
Implemented in 60b81fcdb459df003a1462bd2447480c92b2a5bc

2021-07-29 21:53 UTC, Camshaft54 approved these changes
Looks good.

2021-07-29 21:59 UTC, MetalTurtle18 approved these changes
Looks good.

2021-07-30 19:36 UTC, Reevak05 reviewed
Just two tiny things

2021-07-30 19:36 UTC, Reevak05 commented on src/main/kotlin/io/github/reevak05/commands/TranslateCommand.kt
> +                        message = "A fatal error occurred while trying to process this translation request!",
I prefer to not use "!" in error messages to prevent the user feeling like the bot is yelling at them

2021-07-30 19:36 UTC, Reevak05 commented on src/main/kotlin/io/github/reevak05/translator/FlagReactionHandler.kt
> +                            event.channel.sendBotMessage(
I prefer to not use "!" in error messages to prevent the user feeling like the bot is yelling at them

2021-07-30 19:39 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/translator/FlagReactionHandler.kt
> +                            event.channel.sendBotMessage(
Implemented in #78a1afced6460857350775eabd8921e0296bcc09

2021-07-30 19:39 UTC, Camshaft54 commented on src/main/kotlin/io/github/reevak05/commands/TranslateCommand.kt
> +                        message = "A fatal error occurred while trying to process this translation request!",
Implemented in 78a1afced6460857350775eabd8921e0296bcc09

2021-07-30 19:41 UTC, merged